#
###################################
# Site wide configuration
####################################
#
title: pvqu47
email: pvqu47@gmail.com
description: My blog.
url: https://renyuanz.github.io/leonids # the base hostname & protocol for your site
keywords: ["Programming", "CTF", "Linh tinh"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: pvqu47
  avatar: avatar.jpg
  job: "Student in PSA"
  bio: "Yêu cuộc sống"
  email: pvqu47@gmail.com
  disqus-shortname: renyuanzblog
  twitter: quatphu97hhbg #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: renyuanz #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: renyuan-zou-69b7038a #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
