#
###################################
# Site wide configuration
####################################
#
title: _Q's blog_
email: pvqu47@gmail.com
description: _pvqu47_
url: https://pvqu47.github.io # the base hostname & protocol for your site
keywords: ["Programming", "CTF", "Me"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Vietnam/Hanoi
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: _pvqu47_
  avatar: avatar.jpg
  job: "Student in PSA"
  bio: "What you get by achieving your goals, is not as important as, what you become by achieving your goals."
  email: pvqu47@gmail.com
  disqus-shortname: pvq
  twitter: quatphu97hhbg #username
  facebook: pvqu47
  google:
    plus: #username
    analytics: A
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: pvqu47 #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: r #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
